In [ ]:
Dataset questions:

#Display the first 10 rows of the dataset.

#Find how many rows and columns are present in the dataset.

#Show all column names in the dataset.

#Check the datatype of each column.

2️⃣ Selection & Filtering

#Display only the columns Name, Category, and Color.

#Show all vegetables that belong to the Root category.

#Find all vegetables that are Green in color.

#Display vegetables available only in Summer season.

3️⃣ Conditional Queries

#Find vegetables whose Shelf Life (days) is greater than 30 days.

#Show vegetables whose Origin is South America.

#Display vegetables that require Refrigeration storage.

4️⃣ Sorting

#Sort the dataset by Shelf Life (days) in descending order.

#Sort vegetables alphabetically by Name.

5️⃣ Aggregation (Important for Interview 🔥)

#Count how many vegetables are present in each Category (Root, Leafy, Fruit, etc.).

#Find the average shelf life of vegetables in the dataset.

In [ ]:
import pandas as pd
df=pd.read_csv('d:/vegetables Dataset.csv')
df.head(10)

,Vegetable ID,Name,Scientific Name,Category,Color,Season,Origin,Nutritional Value (per 100g),Price (per kg),Availability,Shelf Life (days),Storage Requirements,Growing Conditions,Health Benefits,Common Varieties
0,1,Carrot,Daucus carota,Root,Orange,Winter,Middle East,"41 kcal, 0.9g protein, 2.8g fiber",$1.50,Year-round,30,Refrigeration,"Well-drained soil, full sunlight","Improves vision, rich in Vitamin A","Nantes, Imperator, Chantenay"
1,2,Spinach,Spinacia oleracea,Leafy,Green,Spring/Fall,Central Asia,"23 kcal, 2.9g protein, 2.2g fiber",$2.00,Year-round,7,Refrigeration,"Moist soil, partial shade","High in iron, good for bone health","Savoy, Flat-leaf, Semi-savoy"
2,3,Tomato,Solanum lycopersicum,Fruit,Red,Summer,South America,"18 kcal, 0.9g protein, 1.2g fiber",$3.00,Seasonal,7,"Cool, dry place","Well-drained soil, full sunlight","Rich in antioxidants, supports heart health","Roma, Cherry, Beefsteak"
3,4,Broccoli,Brassica oleracea,Flower,Green,Fall/Winter,Mediterranean,"34 kcal, 2.8g protein, 2.6g fiber",$2.50,Year-round,10,Refrigeration,"Cool climate, well-drained soil","Boosts immune system, rich in Vitamin C","Calabrese, Sprouting, Romanesco"
4,5,Potato,Solanum tuberosum,Tuber,Brown,Fall,South America,"77 kcal, 2g protein, 2.2g fiber",$1.20,Year-round,60,"Cool, dark place","Loose soil, moderate watering","Provides energy, good source of potassium","Russet, Yukon Gold, Red"
5,6,Bell Pepper,Capsicum annuum,Fruit,"Red, Green, Yellow",Summer,Central America,"31 kcal, 1g protein, 2.1g fiber",$3.50,Year-round,10,Refrigeration,"Warm climate, full sunlight","Rich in Vitamin C, supports immune system","Green, Red, Yellow, Orange"
6,7,Kale,Brassica oleracea var. sabellica,Leafy,Dark Green,Fall/Winter,Europe,"49 kcal, 4.3g protein, 2g fiber",$5.00,Year-round,7,Refrigeration,"Cool climate, rich soil","High in antioxidants, promotes heart health","Curly, Lacinato, Red Russian"
7,8,Eggplant,Solanum melongena,Fruit,Purple,Summer,India,"25 kcal, 1g protein, 3g fiber",$2.20,Year-round,7,"Cool, dry place","Warm climate, well-drained soil","Supports brain health, high in fiber","Black Beauty, Japanese, Graffiti"
8,9,Zucchini,Cucurbita pepo,Fruit,Green,Summer,Central America,"17 kcal, 1.2g protein, 1g fiber",$1.80,Seasonal,5,Refrigeration,"Warm climate, well-drained soil","Low in calories, supports digestion","Black Zucchini, Round, Yellow"
9,10,Cauliflower,Brassica oleracea var. botrytis,Flower,White,Fall/Winter,Mediterranean,"25 kcal, 1.9g protein, 2g fiber",$3.00,Year-round,10,Refrigeration,"Cool climate, rich soil","Rich in fiber, supports digestive health","White, Purple, Romanesco"

In [ ]:
df.info

<bound method DataFrame.info of      Vegetable ID           Name                 Scientific Name Category  \
0               1         Carrot                   Daucus carota     Root
1               2        Spinach               Spinacia oleracea    Leafy
2               3         Tomato            Solanum lycopersicum    Fruit
3               4       Broccoli               Brassica oleracea   Flower
4               5         Potato               Solanum tuberosum    Tuber
..            ...            ...                             ...      ...
145           146  Korean Radish  Raphanus sativus var. koreanus     Root
146            47        Chervil           Anthriscus cerefolium     Herb
147           148       Amaranth                 Amaranthus spp.    Leafy
148           149         Nettle                   Urtica dioica    Leafy
149           150            Oca                 Oxalis tuberosa    Tuber

           Color         Season         Origin  \
0         Orange         Winter    Middle East
1          Green    Spring/Fall   Central Asia
2            Red         Summer  South America
3          Green    Fall/Winter  Mediterranean
4          Brown           Fall  South America
..           ...            ...            ...
145        White         Winter          Korea
146        Green  Spring/Summer         Europe
147   Green, Red         Summer       Americas
148        Green         Spring         Europe
149  Red, Yellow           Fall          Andes

          Nutritional Value (per 100g) Price (per kg) Availability  \
0    41 kcal, 0.9g protein, 2.8g fiber         $1.50    Year-round
1    23 kcal, 2.9g protein, 2.2g fiber         $2.00    Year-round
2    18 kcal, 0.9g protein, 1.2g fiber         $3.00      Seasonal
3    34 kcal, 2.8g protein, 2.6g fiber         $2.50    Year-round
4      77 kcal, 2g protein, 2.2g fiber         $1.20    Year-round
..                                 ...            ...          ...
145      15 kcal, 1g protein, 2g fiber         $2.50      Seasonal
146    17 kcal, 1g protein, 1.2g fiber         $6.00      Seasonal
147      23 kcal, 2g protein, 3g fiber         $6.00    Year-round
148  42 kcal, 2.5g protein, 6.9g fiber         $5.00      Seasonal
149  72 kcal, 1.3g protein, 2.2g fiber         $8.00      Seasonal

     Shelf Life (days) Storage Requirements                Growing Conditions  \
0                   30        Refrigeration  Well-drained soil, full sunlight
1                    7        Refrigeration         Moist soil, partial shade
2                    7      Cool, dry place  Well-drained soil, full sunlight
3                   10        Refrigeration   Cool climate, well-drained soil
4                   60     Cool, dark place     Loose soil, moderate watering
..                 ...                  ...                               ...
145                 10        Refrigeration   Cool climate, well-drained soil
146                  5        Refrigeration  Well-drained soil, full sunlight
147                  7        Refrigeration   Warm climate, well-drained soil
148                  5        Refrigeration          Cool, shaded environment
149                 10      Cool, dry place  Well-drained soil, full sunlight

                                       Health Benefits  \
0                   Improves vision, rich in Vitamin A
1                   High in iron, good for bone health
2          Rich in antioxidants, supports heart health
3              Boosts immune system, rich in Vitamin C
4            Provides energy, good source of potassium
..                                                 ...
145              High in Vitamin C, supports digestion
146       Rich in vitamins A and C, supports digestion
147   Rich in vitamins A and C, supports immune health
148  Rich in vitamins and minerals, supports blood ...
149              High in Vitamin C, supports digestion

                     Common Varieties
0        Nantes, Imperator, Chantenay
1        Savoy, Flat-leaf, Semi-savoy
2             Roma, Cherry, Beefsteak
3     Calabrese, Sprouting, Romanesco
4             Russet, Yukon Gold, Red
..                                ...
145                 Mu, Korean Daikon
146  Curly Chervil, Flat-leaf Chervil
147      Red Amaranth, Green Amaranth
148    Common Nettle, Stinging Nettle
149     Peruvian Oca, New Zealand Oca

[150 rows x 15 columns]>

In [ ]:
df.columns

Index(['Vegetable ID', 'Name', 'Scientific Name', 'Category', 'Color',
       'Season', 'Origin', 'Nutritional Value (per 100g)', 'Price (per kg)',
       'Availability', 'Shelf Life (days)', 'Storage Requirements',
       'Growing Conditions', 'Health Benefits', 'Common Varieties'],
      dtype='object')

In [ ]:
df.isnull().sum()

Vegetable ID                    0
Name                            0
Scientific Name                 0
Category                        0
Color                           0
Season                          0
Origin                          0
Nutritional Value (per 100g)    0
Price (per kg)                  0
Availability                    0
Shelf Life (days)               0
Storage Requirements            0
Growing Conditions              0
Health Benefits                 0
Common Varieties                0
dtype: int64

In [ ]:
rows=df.loc[0]
print(rows)

Vegetable ID                                                     1
Name                                                        Carrot
Scientific Name                                      Daucus carota
Category                                                      Root
Color                                                       Orange
Season                                                      Winter
Origin                                                 Middle East
Nutritional Value (per 100g)     41 kcal, 0.9g protein, 2.8g fiber
Price (per kg)                                              $1.50
Availability                                            Year-round
Shelf Life (days)                                               30
Storage Requirements                                 Refrigeration
Growing Conditions                Well-drained soil, full sunlight
Health Benefits                 Improves vision, rich in Vitamin A
Common Varieties                      Nantes, Imperator, Chantenay
Name: 0, dtype: object

In [ ]:
df.columns = [i.lower().replace(' ', '_').replace('/', '_') for i in df.columns]
df.head()

,vegetable_id,name,scientific_name,category,color,season,origin,nutritional_value_(per_100g),price_(per_kg),availability,shelf_life_(days),storage_requirements,growing_conditions,health_benefits,common_varieties
0,1,Carrot,Daucus carota,Root,Orange,Winter,Middle East,"41 kcal, 0.9g protein, 2.8g fiber",$1.50,Year-round,30,Refrigeration,"Well-drained soil, full sunlight","Improves vision, rich in Vitamin A","Nantes, Imperator, Chantenay"
1,2,Spinach,Spinacia oleracea,Leafy,Green,Spring/Fall,Central Asia,"23 kcal, 2.9g protein, 2.2g fiber",$2.00,Year-round,7,Refrigeration,"Moist soil, partial shade","High in iron, good for bone health","Savoy, Flat-leaf, Semi-savoy"
2,3,Tomato,Solanum lycopersicum,Fruit,Red,Summer,South America,"18 kcal, 0.9g protein, 1.2g fiber",$3.00,Seasonal,7,"Cool, dry place","Well-drained soil, full sunlight","Rich in antioxidants, supports heart health","Roma, Cherry, Beefsteak"
3,4,Broccoli,Brassica oleracea,Flower,Green,Fall/Winter,Mediterranean,"34 kcal, 2.8g protein, 2.6g fiber",$2.50,Year-round,10,Refrigeration,"Cool climate, well-drained soil","Boosts immune system, rich in Vitamin C","Calabrese, Sprouting, Romanesco"
4,5,Potato,Solanum tuberosum,Tuber,Brown,Fall,South America,"77 kcal, 2g protein, 2.2g fiber",$1.20,Year-round,60,"Cool, dark place","Loose soil, moderate watering","Provides energy, good source of potassium","Russet, Yukon Gold, Red"

In [ ]:
df.describe

<bound method NDFrame.describe of      Vegetable ID           Name                 Scientific Name Category  \
0               1         Carrot                   Daucus carota     Root
1               2        Spinach               Spinacia oleracea    Leafy
2               3         Tomato            Solanum lycopersicum    Fruit
3               4       Broccoli               Brassica oleracea   Flower
4               5         Potato               Solanum tuberosum    Tuber
..            ...            ...                             ...      ...
145           146  Korean Radish  Raphanus sativus var. koreanus     Root
146            47        Chervil           Anthriscus cerefolium     Herb
147           148       Amaranth                 Amaranthus spp.    Leafy
148           149         Nettle                   Urtica dioica    Leafy
149           150            Oca                 Oxalis tuberosa    Tuber

           Color         Season         Origin  \
0         Orange         Winter    Middle East
1          Green    Spring/Fall   Central Asia
2            Red         Summer  South America
3          Green    Fall/Winter  Mediterranean
4          Brown           Fall  South America
..           ...            ...            ...
145        White         Winter          Korea
146        Green  Spring/Summer         Europe
147   Green, Red         Summer       Americas
148        Green         Spring         Europe
149  Red, Yellow           Fall          Andes

          Nutritional Value (per 100g) Price (per kg) Availability  \
0    41 kcal, 0.9g protein, 2.8g fiber         $1.50    Year-round
1    23 kcal, 2.9g protein, 2.2g fiber         $2.00    Year-round
2    18 kcal, 0.9g protein, 1.2g fiber         $3.00      Seasonal
3    34 kcal, 2.8g protein, 2.6g fiber         $2.50    Year-round
4      77 kcal, 2g protein, 2.2g fiber         $1.20    Year-round
..                                 ...            ...          ...
145      15 kcal, 1g protein, 2g fiber         $2.50      Seasonal
146    17 kcal, 1g protein, 1.2g fiber         $6.00      Seasonal
147      23 kcal, 2g protein, 3g fiber         $6.00    Year-round
148  42 kcal, 2.5g protein, 6.9g fiber         $5.00      Seasonal
149  72 kcal, 1.3g protein, 2.2g fiber         $8.00      Seasonal

     Shelf Life (days) Storage Requirements                Growing Conditions  \
0                   30        Refrigeration  Well-drained soil, full sunlight
1                    7        Refrigeration         Moist soil, partial shade
2                    7      Cool, dry place  Well-drained soil, full sunlight
3                   10        Refrigeration   Cool climate, well-drained soil
4                   60     Cool, dark place     Loose soil, moderate watering
..                 ...                  ...                               ...
145                 10        Refrigeration   Cool climate, well-drained soil
146                  5        Refrigeration  Well-drained soil, full sunlight
147                  7        Refrigeration   Warm climate, well-drained soil
148                  5        Refrigeration          Cool, shaded environment
149                 10      Cool, dry place  Well-drained soil, full sunlight

                                       Health Benefits  \
0                   Improves vision, rich in Vitamin A
1                   High in iron, good for bone health
2          Rich in antioxidants, supports heart health
3              Boosts immune system, rich in Vitamin C
4            Provides energy, good source of potassium
..                                                 ...
145              High in Vitamin C, supports digestion
146       Rich in vitamins A and C, supports digestion
147   Rich in vitamins A and C, supports immune health
148  Rich in vitamins and minerals, supports blood ...
149              High in Vitamin C, supports digestion

                     Common Varieties
0        Nantes, Imperator, Chantenay
1        Savoy, Flat-leaf, Semi-savoy
2             Roma, Cherry, Beefsteak
3     Calabrese, Sprouting, Romanesco
4             Russet, Yukon Gold, Red
..                                ...
145                 Mu, Korean Daikon
146  Curly Chervil, Flat-leaf Chervil
147      Red Amaranth, Green Amaranth
148    Common Nettle, Stinging Nettle
149     Peruvian Oca, New Zealand Oca

[150 rows x 15 columns]>

In [ ]:
df.dtypes

vegetable_id                     int64
name                            object
scientific_name                 object
category                        object
color                           object
season                          object
origin                          object
nutritional_value_(per_100g)    object
price_(per_kg)                  object
availability                    object
shelf_life_(days)                int64
storage_requirements            object
growing_conditions              object
health_benefits                 object
common_varieties                object
dtype: object

In [ ]:
df.columns

Index(['vegetable_id', 'name', 'scientific_name', 'category', 'color',
       'season', 'origin', 'nutritional_value_(per_100g)', 'price_(per_kg)',
       'availability', 'shelf_life_(days)', 'storage_requirements',
       'growing_conditions', 'health_benefits', 'common_varieties'],
      dtype='object')

In [ ]:
df[['name', 'category', 'color']]

              name category        color
0           Carrot     Root       Orange
1          Spinach    Leafy        Green
2           Tomato    Fruit          Red
3         Broccoli   Flower        Green
4           Potato    Tuber        Brown
..             ...      ...          ...
145  Korean Radish     Root        White
146        Chervil     Herb        Green
147       Amaranth    Leafy   Green, Red
148         Nettle    Leafy        Green
149            Oca    Tuber  Red, Yellow

[150 rows x 3 columns]

In [ ]:
df[df['category'] == 'Root']

,vegetable_id,name,scientific_name,category,color,season,origin,nutritional_value_(per_100g),price_(per_kg),availability,shelf_life_(days),storage_requirements,growing_conditions,health_benefits,common_varieties
0,1,Carrot,Daucus carota,Root,Orange,Winter,Middle East,"41 kcal, 0.9g protein, 2.8g fiber",$1.50,Year-round,30,Refrigeration,"Well-drained soil, full sunlight","Improves vision, rich in Vitamin A","Nantes, Imperator, Chantenay"
16,17,Beetroot,Beta vulgaris,Root,Red,Fall,Europe,"43 kcal, 1.6g protein, 2.8g fiber",$2.50,Seasonal,14,"Cool, dry place","Well-drained soil, full sunlight","Rich in nitrates, supports heart health","Detroit Dark Red, Chioggia, Golden"
17,18,Radish,Raphanus sativus,Root,"Red, White",Spring,Southeast Asia,"16 kcal, 0.7g protein, 1.6g fiber",$2.00,Seasonal,10,Refrigeration,"Loose soil, moderate watering","Supports digestion, high in antioxidants","Red Globe, Daikon, French Breakfast"
25,26,Turnip,Brassica rapa,Root,"White, Purple",Fall/Winter,Europe,"28 kcal, 0.9g protein, 1.8g fiber",$1.50,Seasonal,14,"Cool, dry place","Cool climate, moist soil","Rich in Vitamin C, supports digestion","Purple Top, Golden Ball, Scarlet Queen"
33,34,Parsnip,Pastinaca sativa,Root,White,Fall/Winter,Europe,"75 kcal, 1.2g protein, 4.9g fiber",$2.20,Seasonal,30,"Cool, dry place","Well-drained soil, full sunlight","High in potassium, supports heart health","Hollow Crown, Harris Model, All American"
36,37,Rutabaga,Brassica napus var. napobrassica,Root,"Yellow, Purple",Fall/Winter,Scandinavia,"37 kcal, 1.2g protein, 2.3g fiber",$1.80,Seasonal,30,"Cool, dry place","Well-drained soil, full sunlight","Rich in Vitamin C, supports immune health","American Purple Top, Laurentian"
37,38,Kohlrabi,Brassica oleracea var. gongylodes,Root,"Green, Purple",Fall/Winter,Europe,"27 kcal, 1.7g protein, 3.6g fiber",$2.50,Year-round,14,Refrigeration,"Cool climate, moist soil","Supports digestion, high in fiber","Purple Vienna, White Vienna, Gigante"
38,39,Jicama,Pachyrhizus erosus,Root,Brown,Summer,Central America,"38 kcal, 0.7g protein, 4.9g fiber",$3.00,Year-round,14,"Cool, dry place","Well-drained soil, full sunlight","Low in calories, supports digestive health","Mexican Turnip, Water Chestnut"
48,49,Daikon Radish,Raphanus sativus var. longipinnatus,Root,White,Winter,East Asia,"18 kcal, 0.6g protein, 1.6g fiber",$2.00,Seasonal,14,Refrigeration,"Cool climate, well-drained soil","High in Vitamin C, supports digestion","Minowase, Miyashige, Alpine"
56,57,Kohlrabi,Brassica oleracea var. gongylodes,Root,"Green, Purple",Fall/Winter,Europe,"27 kcal, 1.7g protein, 3.6g fiber",$2.50,Year-round,14,Refrigeration,"Cool climate, moist soil","Supports digestion, high in fiber","Purple Vienna, White Vienna, Gigante"
57,58,Celeriac,Apium graveolens var. rapaceum,Root,"Brown, White",Fall/Winter,Mediterranean,"42 kcal, 1.5g protein, 1.8g fiber",$3.50,Seasonal,30,"Cool, dry place","Cool climate, rich soil","Supports bone health, rich in Vitamin K","Brilliant, Giant Prague, Monarch"
58,59,Salsify,Tragopogon porrifolius,Root,"Brown, White",Fall,Mediterranean,"82 kcal, 3g protein, 3.3g fiber",$6.00,Seasonal,14,"Cool, dry place","Well-drained soil, full sunlight","Supports digestion, high in fiber","Mammoth Sandwich Island, Black"
74,75,Black Radish,Raphanus sativus var. niger,Root,"Black, White",Winter,Eastern Europe,"20 kcal, 0.8g protein, 1.5g fiber",$3.50,Seasonal,14,Refrigeration,"Cool climate, well-drained soil","Supports digestion, high in fiber","Noir Long Maraîcher, Round Spanish, Nero Tondo"
79,80,Kohlrabi,Brassica oleracea var. gongylodes,Root,"Green, Purple",Fall/Winter,Europe,"27 kcal, 1.7g protein, 3.6g fiber",$2.50,Year-round,14,Refrigeration,"Cool climate, moist soil","Supports digestion, high in fiber","Purple Vienna, White Vienna, Gigante"
90,91,Kudzu,Pueraria montana,Root,Brown,Summer,Asia,"100 kcal, 2g protein, 5g fiber",$7.00,Seasonal,30,"Cool, dry place","Warm climate, well-drained soil","High in fiber, supports digestive health","Japanese Kudzu, Arrowroot"
97,98,Daikon Radish,Raphanus sativus var. longipinnatus,Root,White,Winter,East Asia,"18 kcal, 0.6g protein, 1.6g fiber",$2.00,Seasonal,14,Refrigeration,"Cool climate, well-drained soil","High in Vitamin C, supports digestion","Minowase, Miyashige, Alpine"
102,103,Celery Root,Apium graveolens var. rapaceum,Root,"Brown, White",Fall/Winter,Mediterranean,"42 kcal, 1.5g protein, 1.8g fiber",$3.50,Seasonal,30,"Cool, dry place","Cool climate, rich soil","Supports bone health, rich in Vitamin K","Brilliant, Giant Prague, Monarch"
105,6,Celeriac,Apium graveolens var. rapaceum,Root,"Brown, White",Fall/Winter,Mediterranean,"42 kcal, 1.5g protein, 1.8g fiber",$3.50,Seasonal,30,"Cool, dry place","Cool climate, rich soil","Supports bone health, rich in Vitamin K","Brilliant, Giant Prague, Monarch"
115,116,Rutabaga,Brassica napus var. rapa,Root,Yellow,Fall/Winter,Europe,"37 kcal, 1g protein, 1.8g fiber",$2.50,Year-round,14,"Cool, dry place","Well-drained soil, full sunlight","Supports digestion, rich in Vitamin C","Swede, Yellow Turnip"
116,117,Wasabi,Wasabia japonica,Root,Green,Year-round,Japan,"50 kcal, 1g protein, 1.8g fiber",$100.00,Year-round,7,Refrigeration,"Cool, shaded environment","Supports digestion, rich in antioxidants",Japanese Horseradish
121,122,White Radish,Raphanus sativus,Root,White,Winter,Asia,"16 kcal, 0.6g protein, 1.6g fiber",$2.00,Seasonal,14,Refrigeration,"Cool climate, well-drained soil","High in Vitamin C, supports digestion","Daikon, Long White Radish"
129,130,Kohlrabi,Brassica oleracea var. gongylodes,Root,"Green, Purple",Fall/Winter,Europe,"27 kcal, 1.7g protein, 2.3g fiber",$3.50,Seasonal,14,"Cool, dry place","Well-drained soil, full sunlight","Supports digestion, rich in Vitamin C","White, Purple, German Turnip"
131,132,Salsify,Tragopogon porrifolius,Root,Brown,Fall/Winter,Europe,"73 kcal, 2g protein, 2g fiber",$4.00,Seasonal,14,"Cool, dry place","Well-drained soil, full sunlight","Supports digestion, high in potassium","Oyster Plant, Vegetable Oyster"
141,142,Daikon Radish,Raphanus sativus var. longipinnatus,Root,White,Winter,East Asia,"18 kcal, 0.6g protein, 1.6g fiber",$2.00,Seasonal,14,Refrigeration,"Cool climate, well-drained soil","High in Vitamin C, supports digestion","Minowase, Miyashige, Alpine"
145,146,Korean Radish,Raphanus sativus var. koreanus,Root,White,Winter,Korea,"15 kcal, 1g protein, 2g fiber",$2.50,Seasonal,10,Refrigeration,"Cool climate, well-drained soil","High in Vitamin C, supports digestion","Mu, Korean Daikon"

In [ ]:
df[df['color'] == 'Green']

,vegetable_id,name,scientific_name,category,color,season,origin,nutritional_value_(per_100g),price_(per_kg),availability,shelf_life_(days),storage_requirements,growing_conditions,health_benefits,common_varieties
1,2,Spinach,Spinacia oleracea,Leafy,Green,Spring/Fall,Central Asia,"23 kcal, 2.9g protein, 2.2g fiber",$2.00,Year-round,7,Refrigeration,"Moist soil, partial shade","High in iron, good for bone health","Savoy, Flat-leaf, Semi-savoy"
3,4,Broccoli,Brassica oleracea,Flower,Green,Fall/Winter,Mediterranean,"34 kcal, 2.8g protein, 2.6g fiber",$2.50,Year-round,10,Refrigeration,"Cool climate, well-drained soil","Boosts immune system, rich in Vitamin C","Calabrese, Sprouting, Romanesco"
8,9,Zucchini,Cucurbita pepo,Fruit,Green,Summer,Central America,"17 kcal, 1.2g protein, 1g fiber",$1.80,Seasonal,5,Refrigeration,"Warm climate, well-drained soil","Low in calories, supports digestion","Black Zucchini, Round, Yellow"
12,13,Green Beans,Phaseolus vulgaris,Legume,Green,Summer,South America,"31 kcal, 1.8g protein, 2.7g fiber",$2.00,Year-round,7,Refrigeration,"Warm climate, well-drained soil","High in Vitamin K, supports bone health","Bush, Pole, French"
15,16,Lettuce,Lactuca sativa,Leafy,Green,Spring,Mediterranean,"15 kcal, 1.4g protein, 1.3g fiber",$1.00,Year-round,5,Refrigeration,"Cool climate, moist soil","Low in calories, supports digestion","Butterhead, Romaine, Iceberg"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,143,Land Cress,Barbarea vulgaris,Leafy,Green,Winter,Europe,"18 kcal, 1.8g protein, 2g fiber",$5.00,Seasonal,7,Refrigeration,"Cool climate, well-drained soil","Rich in vitamins A and C, supports immune health","Winter Cress, American Cress"
143,144,Poblano Pepper,Capsicum annuum,Fruit,Green,Summer,Mexico,"20 kcal, 0.9g protein, 1.7g fiber",$4.00,Year-round,7,Refrigeration,"Warm climate, well-drained soil","Rich in Vitamin C, supports immune health","Pasilla, Ancho"
144,145,Chayote,Sechium edule,Fruit,Green,Summer,Central America,"19 kcal, 0.8g protein, 2.2g fiber",$4.00,Year-round,14,"Cool, dry place","Well-drained soil, full sunlight","Supports digestion, rich in Vitamin C","Smooth, Spiny, Pear Squash"
146,47,Chervil,Anthriscus cerefolium,Herb,Green,Spring/Summer,Europe,"17 kcal, 1g protein, 1.2g fiber",$6.00,Seasonal,5,Refrigeration,"Well-drained soil, full sunlight","Rich in vitamins A and C, supports digestion","Curly Chervil, Flat-leaf Chervil"
148,149,Nettle,Urtica dioica,Leafy,Green,Spring,Europe,"42 kcal, 2.5g protein, 6.9g fiber",$5.00,Seasonal,5,Refrigeration,"Cool, shaded environment","Rich in vitamins and minerals, supports blood ...","Common Nettle, Stinging Nettle"

In [ ]:
df[df['season'] == 'Summer']

,vegetable_id,name,scientific_name,category,color,season,origin,nutritional_value_(per_100g),price_(per_kg),availability,shelf_life_(days),storage_requirements,growing_conditions,health_benefits,common_varieties
2,3,Tomato,Solanum lycopersicum,Fruit,Red,Summer,South America,"18 kcal, 0.9g protein, 1.2g fiber",$3.00,Seasonal,7,"Cool, dry place","Well-drained soil, full sunlight","Rich in antioxidants, supports heart health","Roma, Cherry, Beefsteak"
5,6,Bell Pepper,Capsicum annuum,Fruit,"Red, Green, Yellow",Summer,Central America,"31 kcal, 1g protein, 2.1g fiber",$3.50,Year-round,10,Refrigeration,"Warm climate, full sunlight","Rich in Vitamin C, supports immune system","Green, Red, Yellow, Orange"
7,8,Eggplant,Solanum melongena,Fruit,Purple,Summer,India,"25 kcal, 1g protein, 3g fiber",$2.20,Year-round,7,"Cool, dry place","Warm climate, well-drained soil","Supports brain health, high in fiber","Black Beauty, Japanese, Graffiti"
8,9,Zucchini,Cucurbita pepo,Fruit,Green,Summer,Central America,"17 kcal, 1.2g protein, 1g fiber",$1.80,Seasonal,5,Refrigeration,"Warm climate, well-drained soil","Low in calories, supports digestion","Black Zucchini, Round, Yellow"
12,13,Green Beans,Phaseolus vulgaris,Legume,Green,Summer,South America,"31 kcal, 1.8g protein, 2.7g fiber",$2.00,Year-round,7,Refrigeration,"Warm climate, well-drained soil","High in Vitamin K, supports bone health","Bush, Pole, French"
13,14,Onion,Allium cepa,Bulb,"Yellow, Red, White",Summer,Central Asia,"40 kcal, 1.1g protein, 1.7g fiber",$1.20,Year-round,60,"Cool, dry place","Loose soil, moderate watering","Anti-inflammatory, supports heart health","Yellow, Red, White"
20,21,Corn,Zea mays,Grain,Yellow,Summer,Central America,"86 kcal, 3.2g protein, 2.7g fiber",$2.00,Seasonal,7,"Cool, dry place","Warm climate, full sunlight","Good source of energy, high in fiber","Sweet Corn, Flint Corn, Dent Corn"
22,23,Cucumber,Cucumis sativus,Fruit,Green,Summer,South Asia,"16 kcal, 0.7g protein, 0.5g fiber",$1.50,Year-round,7,Refrigeration,"Warm climate, well-drained soil","Hydrating, supports skin health","Slicing, Pickling, Seedless"
26,27,Okra,Abelmoschus esculentus,Fruit,Green,Summer,Africa,"33 kcal, 2g protein, 3.2g fiber",$4.00,Seasonal,7,Refrigeration,"Warm climate, well-drained soil","High in fiber, supports digestive health","Clemson Spineless, Red Burgundy, Annie Oakley"
38,39,Jicama,Pachyrhizus erosus,Root,Brown,Summer,Central America,"38 kcal, 0.7g protein, 4.9g fiber",$3.00,Year-round,14,"Cool, dry place","Well-drained soil, full sunlight","Low in calories, supports digestive health","Mexican Turnip, Water Chestnut"
41,42,Chayote,Sechium edule,Fruit,Green,Summer,Central America,"19 kcal, 0.8g protein, 2.2g fiber",$4.00,Year-round,14,"Cool, dry place","Well-drained soil, full sunlight","Supports digestion, rich in Vitamin C","Smooth, Spiny, Pear Squash"
45,46,Tomatillo,Physalis philadelphica,Fruit,Green,Summer,Mexico,"32 kcal, 1g protein, 1.9g fiber",$4.50,Seasonal,14,"Cool, dry place","Warm climate, well-drained soil","Rich in Vitamin C, supports immune health","Toma Verde, Purple, Rio Grande Verde"
49,50,Bitter Melon,Momordica charantia,Fruit,Green,Summer,India,"17 kcal, 1g protein, 2.6g fiber",$4.00,Seasonal,7,Refrigeration,"Warm climate, well-drained soil","Supports blood sugar regulation, high in Vitam...","Chinese, Indian, White"
54,55,Purslane,Portulaca oleracea,Leafy,Green,Summer,Mediterranean,"16 kcal, 1.3g protein, 1.5g fiber",$4.00,Seasonal,5,Refrigeration,"Well-drained soil, full sunlight","Rich in Omega-3 fatty acids, supports heart he...","Golden, Green, Red"
61,62,Amaranth Greens,Amaranthus spp.,Leafy,"Green, Red",Summer,Central America,"23 kcal, 2.5g protein, 2.1g fiber",$4.50,Seasonal,7,Refrigeration,"Warm climate, rich soil","Rich in protein and iron, supports heart health","Red Garnet, Green Callaloo, Joseph's Coat"
63,64,Tindora,Coccinia grandis,Fruit,Green,Summer,South Asia,"18 kcal, 1.2g protein, 2g fiber",$5.00,Seasonal,7,Refrigeration,"Warm climate, well-drained soil","Supports digestion, rich in Vitamin A","Ivy Gourd, Scarlet Gourd"
64,65,Malabar Spinach,Basella alba,Leafy,"Green, Red",Summer,India,"23 kcal, 2.7g protein, 1.5g fiber",$4.00,Year-round,7,Refrigeration,"Warm climate, well-drained soil","Rich in vitamins A, C, supports eye and skin h...","Green, Red Stem, Creeping Spinach"
66,67,Winged Bean,Psophocarpus tetragonolobus,Legume,Green,Summer,Southeast Asia,"49 kcal, 2.8g protein, 2.2g fiber",$8.00,Seasonal,7,Refrigeration,"Warm climate, well-drained soil","High in protein, supports digestive health","Princess Bean, Goa Bean, Asparagus Pea"
67,68,Snake Gourd,Trichosanthes cucumerina,Fruit,Green,Summer,India,"18 kcal, 1g protein, 2.4g fiber",$4.50,Seasonal,7,Refrigeration,"Warm climate, rich soil","Supports digestion, rich in fiber","Short, Long, White"
72,73,Yardlong Bean,Vigna unguiculata subsp. sesquipedalis,Legume,Green,Summer,Southeast Asia,"47 kcal, 3g protein, 3.6g fiber",$6.00,Seasonal,7,Refrigeration,"Warm climate, well-drained soil","High in protein, supports heart health","Stickless Wonder, Red Noodle, Mosaic"
76,77,Samphire,Salicornia europaea,Succulent,Green,Summer,Coastal regions,"22 kcal, 2.1g protein, 1.8g fiber",$15.00,Seasonal,5,Refrigeration,"Salty soil, coastal climate","Rich in minerals, supports thyroid health","Marsh, Rock, Sea Asparagus"
77,78,Tindora,Coccinia grandis,Fruit,Green,Summer,South Asia,"23 kcal, 1.4g protein, 2g fiber",$5.50,Seasonal,7,Refrigeration,"Warm climate, well-drained soil","Supports digestion, rich in Vitamin A","Ivy Gourd, Kundru, Telakucha"
82,83,Sweet Potato Leaves,Ipomoea batatas,Leafy,"Green, Purple",Summer,Central America,"38 kcal, 2g protein, 2.5g fiber",$3.50,Seasonal,7,Refrigeration,"Warm climate, well-drained soil","Rich in antioxidants, supports heart health","Okinawa, Purple, Georgia Jet"
85,86,Chayote,Sechium edule,Fruit,Green,Summer,Central America,"19 kcal, 0.8g protein, 2.2g fiber",$4.00,Year-round,14,"Cool, dry place","Well-drained soil, full sunlight","Supports digestion, rich in Vitamin C","Smooth, Spiny, Pear Squash"
86,87,Kangkong,Ipomoea aquatica,Leafy,Green,Summer,Southeast Asia,"20 kcal, 2g protein, 1.7g fiber",$3.00,Year-round,7,Refrigeration,"Warm climate, well-drained soil","High in Vitamin A, supports eye health","Water Spinach, Chinese Watercress"
87,88,Amaranth,Amaranthus spp.,Leafy,"Green, Red",Summer,Central America,"23 kcal, 2.5g protein, 2.1g fiber",$4.50,Seasonal,7,Refrigeration,"Warm climate, rich soil","Rich in protein and iron, supports heart health","Red Garnet, Green Callaloo, Joseph's Coat"
90,91,Kudzu,Pueraria montana,Root,Brown,Summer,Asia,"100 kcal, 2g protein, 5g fiber",$7.00,Seasonal,30,"Cool, dry place","Warm climate, well-drained soil","High in fiber, supports digestive health","Japanese Kudzu, Arrowroot"
96,97,Sea Beet,Beta vulgaris subsp. maritima,Leafy,"Green, Red",Summer,Coastal regions,"37 kcal, 1.4g protein, 3.8g fiber",$6.50,Seasonal,7,Refrigeration,"Coastal soil, partial shade","Supports bone health, rich in minerals","Wild Beet, Sea Spinach"
98,99,Sweet Corn,Zea mays,Fruit,Yellow,Summer,Central America,"86 kcal, 3.2g protein, 2.7g fiber",$2.50,Seasonal,7,"Cool, dry place","Warm climate, well-drained soil","Supports energy production, rich in fiber","Silver Queen, Golden Bantam, Popcorn"
109,110,Kangkong,Ipomoea aquatica,Leafy,Green,Summer,Southeast Asia,"20 kcal, 2g protein, 1.7g fiber",$3.00,Year-round,7,Refrigeration,"Warm climate, well-drained soil","High in Vitamin A, supports eye health","Water Spinach, Chinese Watercress"
110,111,Purslane,Portulaca oleracea,Leafy,Green,Summer,Europe,"20 kcal, 1.3g protein, 1.4g fiber",$4.50,Seasonal,5,Refrigeration,"Well-drained soil, full sunlight","Rich in omega-3 fatty acids, supports heart he...","Common Purslane, Red Purslane"
111,112,Celosia,Celosia argentea,Leafy,"Red, Green",Summer,Africa,"30 kcal, 2.1g protein, 1.5g fiber",$5.00,Seasonal,7,Refrigeration,"Warm climate, well-drained soil","Rich in antioxidants, supports immune health","Red Cockscomb, Plumed Celosia"
118,119,Chayote,Sechium edule,Fruit,Green,Summer,Central America,"19 kcal, 0.8g protein, 2.2g fiber",$4.00,Year-round,14,"Cool, dry place","Well-drained soil, full sunlight","Supports digestion, rich in Vitamin C","Smooth, Spiny, Pear Squash"
124,125,Yarrow,Achillea millefolium,Herb,Green,Summer,Europe,"43 kcal, 2.5g protein, 2g fiber",$4.50,Seasonal,7,Refrigeration,"Well-drained soil, full sunlight","Supports digestion, rich in antioxidants","Common Yarrow, Meadow Yarrow"
125,126,Gourd,Lagenaria siceraria,Fruit,"Green, Brown",Summer,Africa,"14 kcal, 0.6g protein, 1.3g fiber",$3.00,Seasonal,14,"Cool, dry place","Well-drained soil, full sunlight","Supports digestion, low in calories","Bottle Gourd, Calabash"
126,127,Yellow Squash,Cucurbita pepo,Fruit,Yellow,Summer,Americas,"16 kcal, 1g protein, 1.4g fiber",$3.00,Seasonal,7,"Cool, dry place","Well-drained soil, full sunlight","High in Vitamin C, supports immune health","Crookneck, Straightneck, Summer Squash"
134,135,Perilla,Perilla frutescens,Herb,Green,Summer,Asia,"43 kcal, 3.5g protein, 2.6g fiber",$7.00,Seasonal,7,Refrigeration,"Well-drained soil, full sunlight","Rich in antioxidants, supports heart health","Shiso, Japanese Basil"
137,138,Nasturtium,Tropaeolum majus,Leafy,"Green, Orange",Summer,South America,"40 kcal, 2g protein, 2g fiber",$5.50,Seasonal,7,Refrigeration,"Well-drained soil, full sunlight","Rich in Vitamin C, supports immune health","Garden Nasturtium, Indian Cress"
138,139,Jute Leaves,Corchorus olitorius,Leafy,Green,Summer,Africa,"30 kcal, 1.5g protein, 2.5g fiber",$6.00,Year-round,7,Refrigeration,"Warm climate, well-drained soil","Rich in antioxidants, supports digestion","Saluyot, Egyptian Spinach"
143,144,Poblano Pepper,Capsicum annuum,Fruit,Green,Summer,Mexico,"20 kcal, 0.9g protein, 1.7g fiber",$4.00,Year-round,7,Refrigeration,"Warm climate, well-drained soil","Rich in Vitamin C, supports immune health","Pasilla, Ancho"
144,145,Chayote,Sechium edule,Fruit,Green,Summer,Central America,"19 kcal, 0.8g protein, 2.2g fiber",$4.00,Year-round,14,"Cool, dry place","Well-drained soil, full sunlight","Supports digestion, rich in Vitamin C","Smooth, Spiny, Pear Squash"
147,148,Amaranth,Amaranthus spp.,Leafy,"Green, Red",Summer,Americas,"23 kcal, 2g protein, 3g fiber",$6.00,Year-round,7,Refrigeration,"Warm climate, well-drained soil","Rich in vitamins A and C, supports immune health","Red Amaranth, Green Amaranth"

In [ ]:
df[df['shelf_life_(days)'] > 30]

,vegetable_id,name,scientific_name,category,color,season,origin,nutritional_value_(per_100g),price_(per_kg),availability,shelf_life_(days),storage_requirements,growing_conditions,health_benefits,common_varieties
4,5,Potato,Solanum tuberosum,Tuber,Brown,Fall,South America,"77 kcal, 2g protein, 2.2g fiber",$1.20,Year-round,60,"Cool, dark place","Loose soil, moderate watering","Provides energy, good source of potassium","Russet, Yukon Gold, Red"
13,14,Onion,Allium cepa,Bulb,"Yellow, Red, White",Summer,Central Asia,"40 kcal, 1.1g protein, 1.7g fiber",$1.20,Year-round,60,"Cool, dry place","Loose soil, moderate watering","Anti-inflammatory, supports heart health","Yellow, Red, White"
14,15,Garlic,Allium sativum,Bulb,White,Fall,Central Asia,"149 kcal, 6.4g protein, 2.1g fiber",$5.00,Year-round,120,"Cool, dry place","Well-drained soil, full sunlight","Boosts immune system, anti-inflammatory","Softneck, Hardneck, Elephant"
18,19,Pumpkin,Cucurbita pepo,Fruit,Orange,Fall,North America,"26 kcal, 1g protein, 0.5g fiber",$1.20,Seasonal,60,"Cool, dry place","Well-drained soil, full sunlight","High in Vitamin A, supports immune system","Sugar Pie, Jack-o'-Lantern, Cinderella"

In [ ]:
df[df['origin'] == 'South America']

,vegetable_id,name,scientific_name,category,color,season,origin,nutritional_value_(per_100g),price_(per_kg),availability,shelf_life_(days),storage_requirements,growing_conditions,health_benefits,common_varieties
2,3,Tomato,Solanum lycopersicum,Fruit,Red,Summer,South America,"18 kcal, 0.9g protein, 1.2g fiber",$3.00,Seasonal,7,"Cool, dry place","Well-drained soil, full sunlight","Rich in antioxidants, supports heart health","Roma, Cherry, Beefsteak"
4,5,Potato,Solanum tuberosum,Tuber,Brown,Fall,South America,"77 kcal, 2g protein, 2.2g fiber",$1.20,Year-round,60,"Cool, dark place","Loose soil, moderate watering","Provides energy, good source of potassium","Russet, Yukon Gold, Red"
12,13,Green Beans,Phaseolus vulgaris,Legume,Green,Summer,South America,"31 kcal, 1.8g protein, 2.7g fiber",$2.00,Year-round,7,Refrigeration,"Warm climate, well-drained soil","High in Vitamin K, supports bone health","Bush, Pole, French"
51,52,Cassava,Manihot esculenta,Tuber,Brown,Year-round,South America,"160 kcal, 1.4g protein, 1.8g fiber",$1.80,Year-round,30,"Cool, dry place","Well-drained soil, full sunlight","High in carbohydrates, supports energy production","Sweet, Bitter, Brazilian"
83,84,Oca,Oxalis tuberosa,Tuber,"Orange, Pink",Fall,South America,"70 kcal, 1.5g protein, 1.8g fiber",$9.00,Seasonal,30,"Cool, dry place","Well-drained soil, full sunlight","High in carbohydrates, supports energy production","New Zealand Yam, Red Oca, Hopin"
95,96,Oca,Oxalis tuberosa,Tuber,"Orange, Pink",Fall,South America,"70 kcal, 1.5g protein, 1.8g fiber",$9.00,Seasonal,30,"Cool, dry place","Well-drained soil, full sunlight","High in carbohydrates, supports energy production","New Zealand Yam, Red Oca, Hopin"
99,100,Cassava,Manihot esculenta,Tuber,Brown,Year-round,South America,"160 kcal, 1.4g protein, 1.8g fiber",$1.80,Year-round,30,"Cool, dry place","Well-drained soil, full sunlight","High in carbohydrates, supports energy production","Sweet, Bitter, Brazilian"
137,138,Nasturtium,Tropaeolum majus,Leafy,"Green, Orange",Summer,South America,"40 kcal, 2g protein, 2g fiber",$5.50,Seasonal,7,Refrigeration,"Well-drained soil, full sunlight","Rich in Vitamin C, supports immune health","Garden Nasturtium, Indian Cress"

In [ ]:
df[df['storage_requirements'] == 'Refrigeration']

,vegetable_id,name,scientific_name,category,color,season,origin,nutritional_value_(per_100g),price_(per_kg),availability,shelf_life_(days),storage_requirements,growing_conditions,health_benefits,common_varieties
0,1,Carrot,Daucus carota,Root,Orange,Winter,Middle East,"41 kcal, 0.9g protein, 2.8g fiber",$1.50,Year-round,30,Refrigeration,"Well-drained soil, full sunlight","Improves vision, rich in Vitamin A","Nantes, Imperator, Chantenay"
1,2,Spinach,Spinacia oleracea,Leafy,Green,Spring/Fall,Central Asia,"23 kcal, 2.9g protein, 2.2g fiber",$2.00,Year-round,7,Refrigeration,"Moist soil, partial shade","High in iron, good for bone health","Savoy, Flat-leaf, Semi-savoy"
3,4,Broccoli,Brassica oleracea,Flower,Green,Fall/Winter,Mediterranean,"34 kcal, 2.8g protein, 2.6g fiber",$2.50,Year-round,10,Refrigeration,"Cool climate, well-drained soil","Boosts immune system, rich in Vitamin C","Calabrese, Sprouting, Romanesco"
5,6,Bell Pepper,Capsicum annuum,Fruit,"Red, Green, Yellow",Summer,Central America,"31 kcal, 1g protein, 2.1g fiber",$3.50,Year-round,10,Refrigeration,"Warm climate, full sunlight","Rich in Vitamin C, supports immune system","Green, Red, Yellow, Orange"
6,7,Kale,Brassica oleracea var. sabellica,Leafy,Dark Green,Fall/Winter,Europe,"49 kcal, 4.3g protein, 2g fiber",$5.00,Year-round,7,Refrigeration,"Cool climate, rich soil","High in antioxidants, promotes heart health","Curly, Lacinato, Red Russian"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,144,Poblano Pepper,Capsicum annuum,Fruit,Green,Summer,Mexico,"20 kcal, 0.9g protein, 1.7g fiber",$4.00,Year-round,7,Refrigeration,"Warm climate, well-drained soil","Rich in Vitamin C, supports immune health","Pasilla, Ancho"
145,146,Korean Radish,Raphanus sativus var. koreanus,Root,White,Winter,Korea,"15 kcal, 1g protein, 2g fiber",$2.50,Seasonal,10,Refrigeration,"Cool climate, well-drained soil","High in Vitamin C, supports digestion","Mu, Korean Daikon"
146,47,Chervil,Anthriscus cerefolium,Herb,Green,Spring/Summer,Europe,"17 kcal, 1g protein, 1.2g fiber",$6.00,Seasonal,5,Refrigeration,"Well-drained soil, full sunlight","Rich in vitamins A and C, supports digestion","Curly Chervil, Flat-leaf Chervil"
147,148,Amaranth,Amaranthus spp.,Leafy,"Green, Red",Summer,Americas,"23 kcal, 2g protein, 3g fiber",$6.00,Year-round,7,Refrigeration,"Warm climate, well-drained soil","Rich in vitamins A and C, supports immune health","Red Amaranth, Green Amaranth"
148,149,Nettle,Urtica dioica,Leafy,Green,Spring,Europe,"42 kcal, 2.5g protein, 6.9g fiber",$5.00,Seasonal,5,Refrigeration,"Cool, shaded environment","Rich in vitamins and minerals, supports blood ...","Common Nettle, Stinging Nettle"

In [ ]:
df.sort_values(by='shelf_life_(days)', ascending=False)

,vegetable_id,name,scientific_name,category,color,season,origin,nutritional_value_(per_100g),price_(per_kg),availability,shelf_life_(days),storage_requirements,growing_conditions,health_benefits,common_varieties
14,15,Garlic,Allium sativum,Bulb,White,Fall,Central Asia,"149 kcal, 6.4g protein, 2.1g fiber",$5.00,Year-round,120,"Cool, dry place","Well-drained soil, full sunlight","Boosts immune system, anti-inflammatory","Softneck, Hardneck, Elephant"
4,5,Potato,Solanum tuberosum,Tuber,Brown,Fall,South America,"77 kcal, 2g protein, 2.2g fiber",$1.20,Year-round,60,"Cool, dark place","Loose soil, moderate watering","Provides energy, good source of potassium","Russet, Yukon Gold, Red"
13,14,Onion,Allium cepa,Bulb,"Yellow, Red, White",Summer,Central Asia,"40 kcal, 1.1g protein, 1.7g fiber",$1.20,Year-round,60,"Cool, dry place","Loose soil, moderate watering","Anti-inflammatory, supports heart health","Yellow, Red, White"
18,19,Pumpkin,Cucurbita pepo,Fruit,Orange,Fall,North America,"26 kcal, 1g protein, 0.5g fiber",$1.20,Seasonal,60,"Cool, dry place","Well-drained soil, full sunlight","High in Vitamin A, supports immune system","Sugar Pie, Jack-o'-Lantern, Cinderella"
11,12,Sweet Potato,Ipomoea batatas,Tuber,Orange,Fall,Central America,"86 kcal, 1.6g protein, 3g fiber",$2.50,Year-round,30,"Cool, dark place","Well-drained soil, full sunlight","Rich in beta-carotene, promotes eye health","Beauregard, Jewel, Japanese"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,114,Chervil,Anthriscus cerefolium,Herb,Green,Spring/Summer,Europe,"17 kcal, 1g protein, 1.2g fiber",$6.00,Seasonal,5,Refrigeration,"Well-drained soil, partial shade","Rich in vitamins A and C, supports digestion","Curly Chervil, Flat-leaf Chervil"
133,134,Sorrel,Rumex acetosa,Leafy,Green,Spring,Europe,"43 kcal, 2g protein, 2.3g fiber",$6.00,Seasonal,5,Refrigeration,"Well-drained soil, full sunlight","High in Vitamin C, supports digestive health","French Sorrel, Garden Sorrel"
132,133,Dandelion Greens,Taraxacum officinale,Leafy,Green,Spring,Europe,"45 kcal, 2.7g protein, 3.5g fiber",$5.00,Seasonal,5,Refrigeration,"Well-drained soil, full sunlight","Rich in vitamins A and C, supports liver health","Common Dandelion, Wild Lettuce"
146,47,Chervil,Anthriscus cerefolium,Herb,Green,Spring/Summer,Europe,"17 kcal, 1g protein, 1.2g fiber",$6.00,Seasonal,5,Refrigeration,"Well-drained soil, full sunlight","Rich in vitamins A and C, supports digestion","Curly Chervil, Flat-leaf Chervil"
148,149,Nettle,Urtica dioica,Leafy,Green,Spring,Europe,"42 kcal, 2.5g protein, 6.9g fiber",$5.00,Seasonal,5,Refrigeration,"Cool, shaded environment","Rich in vitamins and minerals, supports blood ...","Common Nettle, Stinging Nettle"

In [ ]:
df.sort_values(by='Name')

,Vegetable ID,Name,Scientific Name,Category,Color,Season,Origin,Nutritional Value (per 100g),Price (per kg),Availability,Shelf Life (days),Storage Requirements,Growing Conditions,Health Benefits,Common Varieties
47,48,Acorn Squash,Cucurbita pepo var. turbinata,Fruit,"Green, Orange",Fall,Central America,"40 kcal, 1g protein, 2g fiber",$3.00,Seasonal,30,"Cool, dry place","Well-drained soil, full sunlight","Rich in Vitamin A, supports vision health","Table Queen, Gold, Taybelle"
147,148,Amaranth,Amaranthus spp.,Leafy,"Green, Red",Summer,Americas,"23 kcal, 2g protein, 3g fiber",$6.00,Year-round,7,Refrigeration,"Warm climate, well-drained soil","Rich in vitamins A and C, supports immune health","Red Amaranth, Green Amaranth"
87,88,Amaranth,Amaranthus spp.,Leafy,"Green, Red",Summer,Central America,"23 kcal, 2.5g protein, 2.1g fiber",$4.50,Seasonal,7,Refrigeration,"Warm climate, rich soil","Rich in protein and iron, supports heart health","Red Garnet, Green Callaloo, Joseph's Coat"
61,62,Amaranth Greens,Amaranthus spp.,Leafy,"Green, Red",Summer,Central America,"23 kcal, 2.5g protein, 2.1g fiber",$4.50,Seasonal,7,Refrigeration,"Warm climate, rich soil","Rich in protein and iron, supports heart health","Red Garnet, Green Callaloo, Joseph's Coat"
29,30,Artichoke,Cynara scolymus,Flower,Green,Spring,Mediterranean,"47 kcal, 3.3g protein, 5.4g fiber",$7.00,Seasonal,7,Refrigeration,"Cool climate, rich soil","High in antioxidants, supports liver health","Green Globe, Purple of Romagna, Violetta di Ch..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,67,Winged Bean,Psophocarpus tetragonolobus,Legume,Green,Summer,Southeast Asia,"49 kcal, 2.8g protein, 2.2g fiber",$8.00,Seasonal,7,Refrigeration,"Warm climate, well-drained soil","High in protein, supports digestive health","Princess Bean, Goa Bean, Asparagus Pea"
72,73,Yardlong Bean,Vigna unguiculata subsp. sesquipedalis,Legume,Green,Summer,Southeast Asia,"47 kcal, 3g protein, 3.6g fiber",$6.00,Seasonal,7,Refrigeration,"Warm climate, well-drained soil","High in protein, supports heart health","Stickless Wonder, Red Noodle, Mosaic"
124,125,Yarrow,Achillea millefolium,Herb,Green,Summer,Europe,"43 kcal, 2.5g protein, 2g fiber",$4.50,Seasonal,7,Refrigeration,"Well-drained soil, full sunlight","Supports digestion, rich in antioxidants","Common Yarrow, Meadow Yarrow"
126,127,Yellow Squash,Cucurbita pepo,Fruit,Yellow,Summer,Americas,"16 kcal, 1g protein, 1.4g fiber",$3.00,Seasonal,7,"Cool, dry place","Well-drained soil, full sunlight","High in Vitamin C, supports immune health","Crookneck, Straightneck, Summer Squash"
8,9,Zucchini,Cucurbita pepo,Fruit,Green,Summer,Central America,"17 kcal, 1.2g protein, 1g fiber",$1.80,Seasonal,5,Refrigeration,"Warm climate, well-drained soil","Low in calories, supports digestion","Black Zucchini, Round, Yellow"

In [ ]:
df['category'].value_counts()

category
Leafy        50
Root         25
Fruit        22
Tuber        18
Bulb          7
Flower        6
Stem          6
Herb          6
Legume        4
Cactus        3
Grain         1
Succulent     1
Fern          1
Name: count, dtype: int64

In [ ]:
df.groupby('category')['name'].count()

category
Bulb          7
Cactus        3
Fern          1
Flower        6
Fruit        22
Grain         1
Herb          6
Leafy        50
Legume        4
Root         25
Stem          6
Succulent     1
Tuber        18
Name: name, dtype: int64

In [ ]:
df['shelf_life_(days)'].mean()

np.float64(13.006666666666666)

In [ ]:
df.groupby('category')['shelf_life_(days)'].mean()

category
Bulb         32.428571
Cactus        8.000000
Fern          5.000000
Flower        9.000000
Fruit        12.727273
Grain         7.000000
Herb          6.000000
Leafy         7.240000
Legume        6.500000
Root         17.880000
Stem          9.166667
Succulent     5.000000
Tuber        23.500000
Name: shelf_life_(days), dtype: float64

In [ ]:
df.to_csv('D:/cleaned data vegetables.csv',index=False)

In [ ]:
import mysql.connector
import pandas as pd
cn=mysql.connector.connect(host="127.0.0.1",user="root",password="SrIdHaR",database="vegetables")
q="SELECT * FROM vegies"
df=pd.read_sql(q,cn) 
print(df)

     vegetable_id           name                 scientific_name category  \
0               1         Carrot                   Daucus carota     Root
1               2        Spinach               Spinacia oleracea    Leafy
2               3         Tomato            Solanum lycopersicum    Fruit
3               4       Broccoli               Brassica oleracea   Flower
4               5         Potato               Solanum tuberosum    Tuber
..            ...            ...                             ...      ...
145           146  Korean Radish  Raphanus sativus var. koreanus     Root
146            47        Chervil           Anthriscus cerefolium     Herb
147           148       Amaranth                 Amaranthus spp.    Leafy
148           149         Nettle                   Urtica dioica    Leafy
149           150            Oca                 Oxalis tuberosa    Tuber

           color         season         origin  \
0         Orange         Winter    Middle East
1          Green    Spring/Fall   Central Asia
2            Red         Summer  South America
3          Green    Fall/Winter  Mediterranean
4          Brown           Fall  South America
..           ...            ...            ...
145        White         Winter          Korea
146        Green  Spring/Summer         Europe
147   Green, Red         Summer       Americas
148        Green         Spring         Europe
149  Red, Yellow           Fall          Andes

          nutritional_value_(per_100g) price_(per_kg) availability  \
0    41 kcal, 0.9g protein, 2.8g fiber         $1.50    Year-round
1    23 kcal, 2.9g protein, 2.2g fiber         $2.00    Year-round
2    18 kcal, 0.9g protein, 1.2g fiber         $3.00      Seasonal
3    34 kcal, 2.8g protein, 2.6g fiber         $2.50    Year-round
4      77 kcal, 2g protein, 2.2g fiber         $1.20    Year-round
..                                 ...            ...          ...
145      15 kcal, 1g protein, 2g fiber         $2.50      Seasonal
146    17 kcal, 1g protein, 1.2g fiber         $6.00      Seasonal
147      23 kcal, 2g protein, 3g fiber         $6.00    Year-round
148  42 kcal, 2.5g protein, 6.9g fiber         $5.00      Seasonal
149  72 kcal, 1.3g protein, 2.2g fiber         $8.00      Seasonal

     shelf_life_(days) storage_requirements                growing_conditions  \
0                   30        Refrigeration  Well-drained soil, full sunlight
1                    7        Refrigeration         Moist soil, partial shade
2                    7      Cool, dry place  Well-drained soil, full sunlight
3                   10        Refrigeration   Cool climate, well-drained soil
4                   60     Cool, dark place     Loose soil, moderate watering
..                 ...                  ...                               ...
145                 10        Refrigeration   Cool climate, well-drained soil
146                  5        Refrigeration  Well-drained soil, full sunlight
147                  7        Refrigeration   Warm climate, well-drained soil
148                  5        Refrigeration          Cool, shaded environment
149                 10      Cool, dry place  Well-drained soil, full sunlight

                                       health_benefits  \
0                   Improves vision, rich in Vitamin A
1                   High in iron, good for bone health
2          Rich in antioxidants, supports heart health
3              Boosts immune system, rich in Vitamin C
4            Provides energy, good source of potassium
..                                                 ...
145              High in Vitamin C, supports digestion
146       Rich in vitamins A and C, supports digestion
147   Rich in vitamins A and C, supports immune health
148  Rich in vitamins and minerals, supports blood ...
149              High in Vitamin C, supports digestion

                     common_varieties
0        Nantes, Imperator, Chantenay
1        Savoy, Flat-leaf, Semi-savoy
2             Roma, Cherry, Beefsteak
3     Calabrese, Sprouting, Romanesco
4             Russet, Yukon Gold, Red
..                                ...
145                 Mu, Korean Daikon
146  Curly Chervil, Flat-leaf Chervil
147      Red Amaranth, Green Amaranth
148    Common Nettle, Stinging Nettle
149     Peruvian Oca, New Zealand Oca

[150 rows x 15 columns]

C:\Users\srith\AppData\Local\Temp\ipykernel_30428\2478256694.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(q,cn)